### PR TITLE
Bunch of fixes and changes | Ayymemes combobox | NoSmoke | NoScopeBorder | KnifeChanger further improvements |

### PR DESCRIPTION
**Pull request by eeioruewo0iruwe**
Currently you cant click on combo box items that are below the actual window itself, but with this fix, you now can

watch me fuck this up and forget to add something lol

Added Proper NoScopeBorder
and NoSmoke no longer needs to be spoofed

### CODE REVIEW

**Comment by XBoom31** [comment]
dank, ill add them when i'll be home

**Comment by XBoom31** [comment]
last time when i tried to fix those i fucked up the controls, like you were not able to press on anything

**Comment by eeioruewo0iruwe** [comment]
what i added:

29/06/2017 - By eeioruewo0iruwe

-Fixed Online Knife Animations

-Added CZ Skins

-Fixed NoScope

-Improved NoSmoke

-Fixed Head Cross

-Fixed ComboBoxes

**Comment by eeioruewo0iruwe** [comment]
ty for letting me know

**Comment by XBoom31** [comment]
if ayymemes comboboxes are fixed, im gonna add all new skins

**Comment by otvv** [comment]
It's fixed, can confirm.

**Comment by XBoom31** [comment]
im done but i can't sync them, wtf
https://gyazo.com/b5aca5d3f3373e2ffa7a639d14fd42e6

**Comment by otvv** [comment]
tf.

**Pull request merged**
