### PR TITLE
Useless Files

### PR DESCRIPTION
**Pull request by DarkAussieYT**
Removed, useless files, fixed hooks.cpp and menu.cpp

### CODE REVIEW

**Review by xijinRK — CHANGES_REQUESTED** [review]
Delte
./Release

**Comment by DarkAussieYT** [comment]
what does that mean?

**Comment by XBoom31** [comment]
adelete the relase folder

**Comment by DarkAussieYT** [comment]
oh

**Comment by DarkAussieYT** [comment]
fixed

**Pull request closed without merging**
